name: Analyze Event Interests

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    env:
      VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run interest analysis
        run: npm run analyze:events
        
      - name: Check for analysis errors
        if: failure()
        run: |
          echo "Interest analysis failed. Check the logs above for details."
          exit 1
