name: Sync Events

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      VITE_EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run event sync
        run: npm run sync:events
        
      - name: Check for sync errors
        if: failure()
        run: |
          echo "Event sync failed. Check the logs above for details."
          exit 1